site_name: SANS HHC 2021 writeup, Objective 10 (Now Hiring!)
site_author: Joe Ammond (pugpug)
copyright: Joe Ammond - <a href="https://twitter.com/joeammond">@joeammond</a>
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - footnotes
  - attr_list
  - admonition
  - toc:
      permalink: "#"
theme:
  name: material
plugins:
  - search
  - with-pdf:
     author: ''
     copyright: © 2022 Joe Ammond
     #
     cover: true
     back_cover: false
     cover_title: pugpug's 2021 HHC writeup
     cover_subtitle: Reverse-engineering Objective 10
     #custom_template_path: TEMPLATES PATH
     #
     #toc_title: TOC TITLE TEXT
     #heading_shift: false
     #toc_level: 3
     #ordered_chapter_level: 2
     #excludes_children:
     #    - 'release-notes/:upgrading'
     #    - 'release-notes/:changelog'
     #
     #exclude_pages:
     #    - 'bugs/'
     #    - 'appendix/contribute/'
     #convert_iframe:
     #    - src: IFRAME SRC
     #      img: POSTER IMAGE URL
     #      text: ALTERNATE TEXT
     #    - src: ...
     #two_columns_level: 3
     #
     #render_js: true
     #headless_chrome_path: headless-chromium
     #
     output_path: pugpug-HHC-2021-writeup.pdf
     enabled_if_env: ENABLE_PDF_EXPORT
     #
     #debug_html: true
     #show_anchors: true
     #verbose: true
#  - pdf-export:
#      enabled_if_env: ENABLE_PDF_EXPORT
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/joeammond
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/joeammond/
    - icon: fontawesome/brands/github
      link: https://github.com/joeammond
extra_css:
  - css/print.css
nav:
- Home: 'https://ammond.org'
- Introduction: 'index.md'
- Solution: 'solution.md'
- Reverse Engineering the Application Environment: 'reversing.md'
- LFI to RCE... maybe?: 'rce.md'
- Conclustion: 'conclusion.md'
